import { Platform, StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FCFAF3',
  },
  keyboardLayer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingBottom: 34,
    paddingTop: 22,
  },
  backgroundShape: {
    position: 'absolute',
    right: -170,
    top: 96,
    width: 280,
    height: 520,
    borderRadius: 160,
    backgroundColor: 'rgba(224, 239, 219, 0.45)',
  },
  bottomWave: {
    position: 'absolute',
    left: -80,
    right: -80,
    bottom: -86,
    height: 190,
    borderTopWidth: 1,
    borderColor: 'rgba(112, 185, 122, 0.28)',
    borderTopLeftRadius: 260,
    borderTopRightRadius: 260,
    backgroundColor: 'rgba(235, 246, 231, 0.52)',
    transform: [{ rotate: '-7deg' }],
  },
  backButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -8,
  },
  logoWrap: {
    alignItems: 'center',
    marginTop: 2,
  },
  header: {
    alignItems: 'center',
    marginTop: 30,
  },
  title: {
    color: '#0E5A44',
    fontSize: 31,
    lineHeight: 38,
    fontWeight: '900',
    letterSpacing: 0,
    textAlign: 'center',
  },
  subtitle: {
    color: '#34445F',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    marginTop: 12,
    maxWidth: 330,
    textAlign: 'center',
  },
  illustration: {
    alignSelf: 'center',
    width: 116,
    height: 116,
    borderRadius: 58,
    backgroundColor: '#EFF7EB',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 28,
    marginBottom: 24,
  },
  illustrationBadge: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#86C45D',
    borderWidth: 3,
    borderColor: '#FCFAF3',
  },
  formCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E2E6E3',
    backgroundColor: '#FFFFFF',
    padding: 18,
    ...Platform.select({
      web: {
        boxShadow: '0 16px 28px rgba(14, 90, 68, 0.08)',
      },
      default: {
        shadowColor: '#0E5A44',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.08,
        shadowRadius: 18,
        elevation: 3,
      },
    }),
  },
  inputShell: {
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E2E6E3',
    backgroundColor: '#FCFAF8',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  input: {
    flex: 1,
    minHeight: 56,
    color: '#123F38',
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '700',
    includeFontPadding: false,
    letterSpacing: 0,
    paddingHorizontal: 12,
    paddingVertical: 0,
    textAlignVertical: 'center',
  },
  messageText: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '700',
    marginTop: 12,
    textAlign: 'center',
  },
  errorText: {
    color: '#B42318',
  },
  successText: {
    color: '#0B6A2B',
  },
  submitButton: {
    minHeight: 60,
    borderRadius: 20,
    backgroundColor: '#00613F',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 16,
    ...Platform.select({
      web: {
        boxShadow: '0 18px 30px rgba(0, 97, 63, 0.18)',
      },
      default: {
        shadowColor: '#00613F',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.18,
        shadowRadius: 16,
        elevation: 3,
      },
    }),
  },
  submitButtonDisabled: {
    opacity: 0.72,
  },
  submitText: {
    color: '#FFFFFF',
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '900',
    letterSpacing: 0,
  },
  submitArrow: {
    position: 'absolute',
    right: 22,
  },
  securityCard: {
    minHeight: 76,
    borderRadius: 18,
    backgroundColor: '#F1F8EF',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 14,
    marginTop: 20,
  },
  securityIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0E8A57',
    marginRight: 14,
  },
  securityText: {
    flex: 1,
    color: '#0E5A44',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 28,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: '#DCE3DD',
  },
  dividerText: {
    color: '#50615A',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
    marginHorizontal: 12,
    textAlign: 'center',
  },
  loginButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    marginTop: 8,
  },
  loginText: {
    color: '#0E5A44',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '900',
    letterSpacing: 0,
  },
})
