import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FCFAF3',
  },
  image: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  backHitArea: {
    position: 'absolute',
    left: '2%',
    top: '1%',
    width: '9%',
    height: '6%',
  },
  activityHitArea: {
    position: 'absolute',
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    paddingTop: 4,
    paddingRight: 4,
  },
  selectedBadge: {
    width: 18,
    height: 18,
    borderRadius: 999,
    borderWidth: 3,
    borderColor: '#FFFFFF',
    backgroundColor: '#198B20',
  },
  outdoorOne: {
    left: '12.6%',
    top: '37.3%',
    width: '17.5%',
    height: '13.1%',
  },
  outdoorTwo: {
    left: '31.7%',
    top: '37.3%',
    width: '17.5%',
    height: '13.1%',
  },
  outdoorThree: {
    left: '50.6%',
    top: '37.3%',
    width: '17.5%',
    height: '13.1%',
  },
  outdoorFour: {
    left: '69.6%',
    top: '37.3%',
    width: '17.5%',
    height: '13.1%',
  },
  outdoorFive: {
    left: '6.1%',
    top: '51.6%',
    width: '16.3%',
    height: '12.9%',
  },
  outdoorSix: {
    left: '24.1%',
    top: '51.6%',
    width: '16.3%',
    height: '12.9%',
  },
  outdoorSeven: {
    left: '42%',
    top: '51.6%',
    width: '16.3%',
    height: '12.9%',
  },
  outdoorEight: {
    left: '59.5%',
    top: '51.6%',
    width: '16.3%',
    height: '12.9%',
  },
  outdoorNine: {
    left: '77.4%',
    top: '51.6%',
    width: '16.3%',
    height: '12.9%',
  },
  indoorOne: {
    left: '3.1%',
    top: '73.2%',
    width: '14.1%',
    height: '12.4%',
  },
  indoorTwo: {
    left: '18.6%',
    top: '73.2%',
    width: '14.1%',
    height: '12.4%',
  },
  indoorThree: {
    left: '34.2%',
    top: '73.2%',
    width: '14.1%',
    height: '12.4%',
  },
  indoorFour: {
    left: '49.9%',
    top: '73.2%',
    width: '14.1%',
    height: '12.4%',
  },
  indoorFive: {
    left: '65.7%',
    top: '73.2%',
    width: '14.1%',
    height: '12.4%',
  },
  indoorSix: {
    left: '81.3%',
    top: '73.2%',
    width: '14.1%',
    height: '12.4%',
  },
  errorText: {
    position: 'absolute',
    left: '10%',
    right: '10%',
    top: '89%',
    color: '#B42318',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
    textAlign: 'center',
  },
  continueHitArea: {
    position: 'absolute',
    left: '10.7%',
    right: '12.8%',
    top: '92.8%',
    height: '5.5%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  skipHitArea: {
    position: 'absolute',
    left: '34%',
    right: '34%',
    top: '98%',
    height: '2%',
  },
})
