import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FCFAF3',
  },
  keyboardLayer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 24,
  },
  webScrollContent: {
    alignSelf: 'center',
    maxWidth: 520,
    width: '100%',
  },
  backHitArea: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -8,
  },
  logoWrap: {
    alignItems: 'center',
    marginTop: 0,
  },
  titleBlock: {
    alignItems: 'center',
    marginTop: 22,
    marginBottom: 20,
  },
  title: {
    color: '#0E5A44',
    fontSize: 32,
    lineHeight: 38,
    fontWeight: '900',
    letterSpacing: 0,
    textAlign: 'center',
  },
  subtitle: {
    color: '#34445F',
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '600',
    marginTop: 8,
    textAlign: 'center',
  },
  formCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E2E6E3',
    backgroundColor: '#FFFFFF',
    padding: 16,
    shadowColor: '#0E5A44',
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  inputShell: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E2E6E3',
    backgroundColor: '#FCFAF8',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  input: {
    flex: 1,
    minHeight: 56,
    color: '#123F38',
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '700',
    letterSpacing: 0,
    includeFontPadding: false,
    paddingHorizontal: 12,
    paddingVertical: 0,
    paddingTop: 0,
    paddingBottom: 0,
    textAlignVertical: 'center',
  },
  inputFocused: {
    borderColor: '#70B97A',
    backgroundColor: '#F6FBF3',
  },
  forgotPassword: {
    alignSelf: 'flex-end',
    paddingVertical: 8,
    paddingHorizontal: 2,
  },
  forgotPasswordText: {
    color: '#0E5A44',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '800',
  },
  legalAcceptanceBox: {
    alignItems: 'flex-start',
    backgroundColor: '#F7FBF4',
    borderColor: '#DDEBDD',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginBottom: 10,
    marginTop: 4,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  legalCheckbox: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#8CA79D',
    borderRadius: 7,
    borderWidth: 2,
    height: 24,
    justifyContent: 'center',
    marginTop: 1,
    width: 24,
  },
  legalCheckboxChecked: {
    backgroundColor: '#155C47',
    borderColor: '#155C47',
  },
  legalAcceptanceText: {
    color: '#244942',
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 21,
  },
  legalLink: {
    color: '#155C47',
    fontWeight: '900',
  },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorText: {
    color: '#B42318',
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 8,
  },
  infoText: {
    color: '#155C47',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 10,
    marginTop: 2,
  },
  submitButton: {
    minHeight: 60,
    borderRadius: 20,
    backgroundColor: '#00613F',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
    flexDirection: 'row',
    shadowColor: '#00613F',
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  submitButtonDisabled: {
    opacity: 0.72,
  },
  submitText: {
    color: '#FFFFFF',
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '900',
    letterSpacing: 0,
  },
  submitArrow: {
    position: 'absolute',
    right: 22,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 14,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: '#E2E6E3',
  },
  dividerText: {
    color: '#50615A',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
    marginHorizontal: 12,
    textAlign: 'center',
  },
  googleButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#FFFFFF',
    borderColor: '#155C47',
    borderRadius: 20,
    borderWidth: 1.5,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
    minHeight: 60,
    paddingHorizontal: 18,
  },
  googleButtonText: {
    color: '#1F2D2A',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 21,
  },
  createAccount: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
    gap: 8,
  },
  createAccountText: {
    color: '#50615A',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
  },
  createAccountLink: {
    color: '#0E5A44',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '900',
  },
})
