import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F2F8EF',
  },
  webScreen: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 800,
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  webCard: {
    alignItems: 'stretch',
    backgroundColor: '#EAF3E7',
    borderColor: '#D8E7D5',
    borderRadius: 28,
    borderWidth: 1,
    justifyContent: 'space-between',
    maxWidth: 420,
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  webImageBackground: {
    bottom: 0,
    left: 0,
    opacity: 0.24,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 0,
  },
  webContentLayer: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'space-between',
    minHeight: '100%',
    opacity: 1,
    paddingBottom: 42,
    paddingHorizontal: 28,
    paddingTop: 74,
    position: 'relative',
    zIndex: 2,
  },
  webTextBlock: {
    alignItems: 'center',
    width: '100%',
  },
  webEyebrow: {
    color: '#0E5A44',
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 18,
    marginBottom: 14,
    textAlign: 'center',
  },
  webTitle: {
    color: '#0E5A44',
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 40,
    textAlign: 'center',
  },
  webSubtitle: {
    color: '#34445F',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 23,
    marginTop: 14,
    textAlign: 'center',
  },
  webButtonGroup: {
    gap: 12,
    width: '100%',
    zIndex: 3,
  },
  webPrimaryButton: {
    alignItems: 'center',
    backgroundColor: '#00613F',
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 58,
    opacity: 1,
    paddingHorizontal: 20,
  },
  webPrimaryButtonActive: {
    backgroundColor: '#074C35',
  },
  webPrimaryButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 22,
    textAlign: 'center',
  },
  webSecondaryButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#BFD8C3',
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 54,
    opacity: 1,
    paddingHorizontal: 20,
  },
  webSecondaryButtonActive: {
    backgroundColor: '#F5FBF2',
  },
  webSecondaryButtonText: {
    color: '#0E5A44',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 21,
    textAlign: 'center',
  },
  imageFrame: {
    flex: 1,
    width: '100%',
  },
  image: {
    flex: 1,
    height: '100%',
    width: '100%',
  },
  startButtonHitArea: {
    position: 'absolute',
    left: '13%',
    right: '13%',
    top: '80%',
    height: '7%',
  },
  loginButtonHitArea: {
    position: 'absolute',
    left: '25%',
    right: '25%',
    top: '88%',
    height: '5%',
  },
})
