import { Platform, StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FAF8F1',
  },
  keyboard: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    minHeight: '100%',
    overflow: 'hidden',
    paddingBottom: 34,
  },
  content: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingTop: 74,
  },
  backButton: {
    position: 'absolute',
    left: 28,
    top: 50,
    zIndex: 4,
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backIcon: {
    color: '#155C47',
    fontSize: 39,
    lineHeight: 42,
    fontWeight: '500',
  },
  backgroundShape: {
    position: 'absolute',
    right: -190,
    top: 455,
    width: 520,
    height: 550,
    borderRadius: 280,
    backgroundColor: 'rgba(222, 238, 217, 0.62)',
    transform: [{ rotate: '-15deg' }],
  },
  backgroundArc: {
    position: 'absolute',
    left: -42,
    top: 325,
    width: 720,
    height: 250,
    borderTopWidth: 2,
    borderColor: 'rgba(107, 183, 146, 0.38)',
    borderTopLeftRadius: 360,
    borderTopRightRadius: 360,
    transform: [{ rotate: '-7deg' }],
  },
  header: {
    alignItems: 'center',
    marginTop: 58,
  },
  title: {
    color: '#123F38',
    fontSize: 39,
    lineHeight: 48,
    fontWeight: '900',
    letterSpacing: 0,
    textAlign: 'center',
  },
  subtitle: {
    color: '#244942',
    fontSize: 18,
    lineHeight: 26,
    marginTop: 16,
    textAlign: 'center',
  },
  form: {
    width: '100%',
    gap: 16,
    marginTop: 78,
  },
  inputShell: {
    minHeight: 58,
    borderRadius: 999,
    borderWidth: 1.4,
    borderColor: 'rgba(94, 111, 111, 0.24)',
    backgroundColor: 'rgba(255, 255, 255, 0.52)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 22,
    paddingRight: 18,
  },
  inputIcon: {
    width: 38,
    color: '#576767',
    fontSize: 26,
    lineHeight: 30,
    textAlign: 'center',
    marginRight: 16,
  },
  input: {
    flex: 1,
    minHeight: 56,
    color: '#123F38',
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0,
    paddingVertical: 0,
  },
  passwordToggle: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  passwordToggleText: {
    color: '#576767',
    fontSize: 24,
    lineHeight: 28,
  },
  errorText: {
    color: '#9B2F2F',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    textAlign: 'center',
    paddingHorizontal: 12,
  },
  primaryButton: {
    width: '100%',
    minHeight: 70,
    borderRadius: 24,
    backgroundColor: '#155C47',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 12,
    paddingHorizontal: 30,
    ...Platform.select({
      web: {
        boxShadow: '0 20px 34px rgba(21, 92, 71, 0.18)',
      },
      default: {
        shadowColor: '#155C47',
        shadowOffset: { width: 0, height: 18 },
        shadowOpacity: 0.18,
        shadowRadius: 30,
        elevation: 8,
      },
    }),
  },
  primaryButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
  primaryButtonDisabled: {
    opacity: 0.72,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 22,
    lineHeight: 29,
    fontWeight: '900',
    letterSpacing: 0,
  },
  primaryButtonArrow: {
    position: 'absolute',
    right: 34,
    color: '#FFFFFF',
    fontSize: 34,
    lineHeight: 38,
    fontWeight: '500',
  },
  dividerRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginTop: 36,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(93, 106, 103, 0.24)',
  },
  dividerText: {
    color: '#244942',
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
  },
  socialRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 28,
    marginTop: 26,
  },
  socialButton: {
    width: 66,
    height: 66,
    borderRadius: 33,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
    borderWidth: 1,
    borderColor: 'rgba(94, 111, 111, 0.18)',
  },
  socialText: {
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '900',
  },
  googleText: {
    color: '#4285F4',
  },
  appleText: {
    color: '#000000',
    fontSize: 33,
    lineHeight: 38,
  },
  facebookText: {
    color: '#3867B7',
    fontSize: 40,
    lineHeight: 44,
    fontWeight: '900',
  },
  terms: {
    color: '#244942',
    fontSize: 15,
    lineHeight: 23,
    textAlign: 'center',
    marginTop: 34,
  },
  termsStrong: {
    color: '#155C47',
    fontWeight: '900',
  },
  loginButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 28,
  },
  loginText: {
    color: '#244942',
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0,
  },
  loginTextStrong: {
    color: '#2A7057',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
    letterSpacing: 0,
  },
})
